version: '3.8'

name: efp-indexer

networks:
  default:
    driver: bridge

services:
  ping:
    container_name: efp-indexer-ping
    image: bash:latest
    build:
      dockerfile_inline: |
        FROM bash:latest
        WORKDIR /usr/src/app
        RUN apk add --no-cache curl && rm -rf /var/cache/apk/*
        COPY ./scripts/ping.sh /usr/src/app/ping.sh
    command: ./ping.sh
    entrypoint: /usr/local/bin/bash
    networks:
      - default

  anvil:
    container_name: efp-indexer-anvil
    image: ghcr.io/foundry-rs/foundry:latest
    command: anvil
    tty: true
    environment:
      - ANVIL_IP_ADDR=0.0.0.0
    ports:
      - 8545:8545
    networks:
      - default

  database:
    container_name: efp-database
    image: postgres:latest
    restart: always
    networks:
      - default
    command: postgres -c wal_level=logical -c max_replication_slots=20
    volumes:
      - database:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=efp

  indexer:
    container_name: efp-indexer
    depends_on:
      - database
    restart: no
    networks:
      - default
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - DATABASE_URL=${DATABASE_URL:-postgresql://postgres:postgres@efp-database:5432/efp?sslmode=disable}
      - ENABLE_DATABASE_LOGGING=${ENABLE_DATABASE_LOGGING:-true}
      - CHAIN_ID=${CHAIN_ID:-31337}
      - ANKR_ID=${ANKR_ID}
      - INFURA_ID=${INFURA_ID}
      - LLAMAFOLIO_ID=${LLAMAFOLIO_ID}
      - MAINNET_ALCHEMY_ID=${MAINNET_ALCHEMY_ID}
      - SEPOLIA_ALCHEMY_ID=${SEPOLIA_ALCHEMY_ID}
      - OPTIMISM_ALCHEMY_ID=${OPTIMISM_ALCHEMY_ID}
      - ETHEREUM_LOCAL_NODE_URL=${ETHEREUM_LOCAL_NODE_URL:-http://host.docker.internal:8545}
      - ANVIL_ACCOUNT_PRIVATE_KEY=${ANVIL_ACCOUNT_PRIVATE_KEY:-0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80}
      - EFP_CONTRACT_ACCOUNT_METADATA=${EFP_CONTRACT_ACCOUNT_METADATA:-0x5FbDB2315678afecb367f032d93F642f64180aa3}
      - EFP_CONTRACT_LIST_REGISTRY=${EFP_CONTRACT_LIST_REGISTRY:-0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512}
      - EFP_CONTRACT_LIST_RECORDS=${EFP_CONTRACT_LIST_RECORDS:-0x9fE46736679d2D9a65F0992F2272dE9f3c7fa6e0}
      - EFP_CONTRACT_LINT_MINTER=${EFP_CONTRACT_LINT_MINTER:-0xCf7Ed3AccA5a467e9e704C703E8D87F634fB0Fc9}

volumes:
  database:
