version: 2.23.3
name: efp-indexer

# WIP

services:
  database:
    container_name: efp-database
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=efp
    volumes:
      - database:/var/lib/postgresql/data
    ports:
      - 5432:5432
    extra_hosts:
      - "host.docker.internal:host-gateway"
    
  
  indexer:
    container_name: efp-indexer
    depends_on:
      - database
    restart: always
    network_mode: host
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
    environment:
      - DATABASE_URL_POOLED=${DATABASE_URL_POOLED:-postgres://postgres:postgres@database:5432/efp}
      - NODE_ENV=${NODE_ENV:-production}
      - ENABLE_DATABASE_LOGGING=${ENABLE_DATABASE_LOGGING:-true}
      - LLAMAFOLIO_ID=${LLAMAFOLIO_ID}
      - MAINNET_ALCHEMY_ID=${MAINNET_ALCHEMY_ID}
      - ANKR_ID=${ANKR_ID}
      - INFURA_ID=${INFURA_ID}
      - SEPOLIA_ALCHEMY_ID=${SEPOLIA_ALCHEMY_ID}
      - OPTIMISM_ALCHEMY_ID=${OPTIMISM_ALCHEMY_ID}
      - DATABASE_URL=postgres://postgres:postgres@database:5432/efp
      - ANVIL_ACCOUNT_PRIVATE_KEY=${ANVIL_ACCOUNT_PRIVATE_KEY:-0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80}
      - CHAIN_ID=${CHAIN_ID:-31337}
      - EFP_CONTRACT_ACCOUNT_METADATA=${EFP_CONTRACT_ACCOUNT_METADATA:-0x5FbDB2315678afecb367f032d93F642f64180aa3}
      - EFP_CONTRACT_LIST_METADATA=${EFP_CONTRACT_LIST_METADATA:-0x9fE46736679d2D9a65F0992F2272dE9f3c7fa6e0}
      - EFP_CONTRACT_LINT_MINTER=${EFP_CONTRACT_LINT_MINTER:-0x5FC8d32690cc91D4c39d9d3abcBD16989F875707}
      - EFP_CONTRACT_LIST_REGISTRY=${EFP_CONTRACT_LIST_REGISTRY:-0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512}
      - EFP_CONTRACT_LIST_RECORDS=${EFP_CONTRACT_LIST_RECORDS:-0xCf7Ed3AccA5a467e9e704C703E8D87F634fB0Fc9}

    develop:
      watch:
        - action: sync
        - path: src
        - target: /usr/src/app/src
        - ignore:
            - node_modules

volumes:
  database:
