name: 'Lint/Build/Test'
description: 'lint, format, typecheck, build'

inputs:
  skip-build:
    description: 'Skip the build step'
    required: false
    default: 'false'

runs:
  using: composite
  steps:
    - name: '🧹 Lint'
      shell: bash
      run: bun lint

    - name: '🧹 Format'
      shell: bash
      run: bun format

    - name: '🧪 Typecheck'
      shell: bash
      run: bun typecheck

    - name: '🔧 Build'
      shell: bash
      if: ${{ !inputs.skip-build }}
      run: bun run build
